apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-am-new
spec:
  replicas: 2
  selector:
    matchLabels:
      app: am-new
  template:
    metadata:
      labels:
        app: am-new
    spec:
      containers:
      - name: am-new
        image: aaronwang0509/k8sam:1.1.8
        ports:
        - containerPort: 18080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-am-new-service
spec:
  type: NodePort
  ports:
    - port: 18080
      nodePort: 30082
  selector:
    app: am-new