apiVersion: apps/v1
kind: Deployment
metadata:
  name: am-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: am
  template:
    metadata:
      labels:
        app: am
    spec:
      containers:
      - name: am
        image: aaronwang0509/k8sam:1.1.17
        ports:
        - containerPort: 18080

---
apiVersion: v1
kind: Service
metadata:
  name: am-service
spec:
  type: NodePort
  ports:
    - port: 18080
      nodePort: 30080
  selector:
    app: am